### ISSUE TITLE
Custom shapes

### ISSUE THREAD

**Issue by AP2020C** [JakobMick/obsidian-file-indicators#1]
I like your plugin, but I wish it was possible to add new shapes directly from the Obsidian interfaces, in addition to the default 6, without having to edit the source.
With possibility to add also raster icons, fonts or even icons with multiple colors. Not just svg.

**Comment by JakobMick** [comment]
Hey, glad you like the plugin.

I am already working on a feature to add custom shapes. It will probably be limited to svgs though. 

You can try the `Iconize` plugin: [https://github.com/FlorianWoelki/obsidian-iconize](https://github.com/FlorianWoelki/obsidian-iconize)

It offers more features and lets you add custom icon packs. Though i don't know if `Iconize` and `File indicators` are compatible. Let me know if you find out!

**Comment by JakobMick** [comment]
Custom SVG shapes are available in version 1.1.0 👍
